name: Rawhide Build

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '45 5 * * 1'

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: echo "Rawhide builds are currently disabled. Only Fedora 43 x86_64 builds are active."
  
  # rawhideBuilds:
  #   strategy:
  #     matrix:
  #       runs-on-arch: [ubuntu-latest, ubuntu-24.04-arm]
  #       os: [fedora]
  #       version: [rawhide]
  #       dockernamespace: [quay.io/fedora/fedora]
  #   runs-on: ${{ matrix.runs-on-arch }}
  #   container: 
  #     image: ${{ matrix.dockernamespace }}:${{ matrix.version }}
  # 
  #   steps:
  #     - uses: actions/checkout@v4
  # 
  #     - name: Specify Build Target
  #       run: |
  #         echo "SPECIFICTARGET=rawhide" >> $GITHUB_ENV
  #     
  #     - name: Environment variable for OS version
  #       run: |
  #         echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV
  #     
  #     - name: Run CI
  #       run: ci/${{ matrix.os }}.sh