name: Create Release Assets

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.14.11)'
        required: false
        type: string
      release:
        description: 'Release number (e.g., 1) - defaults to Makefile value'
        required: false
        type: string
      create_release:
        description: 'Create GitHub release'
        required: true
        default: true
        type: boolean
  release:
    types:
      - published
  push:
    tags:
      - 'v*'

jobs:  
  buildrpms-x86-64:
    strategy:
      matrix:
        include:
          - os: fedora
            version: 43
            dockernamespace: quay.io/fedora/fedora
          # - os: fedora
          #   version: 40
          #   dockernamespace: quay.io/fedora/fedora
          # - os: fedora
          #   version: 41
          #   dockernamespace: quay.io/fedora/fedora
          # - os: fedora
          #   version: 42
          #   dockernamespace: quay.io/fedora/fedora
          # - os: centos-stream
          #   version: stream9
          #   dockernamespace: quay.io/centos/centos
          # - os: rocky
          #   version: 9
          #   dockernamespace: quay.io/rockylinux/rockylinux
          # - os: rocky
          #   version: 10
          #   dockernamespace: quay.io/rockylinux/rockylinux
          # - os: almalinux
          #   version: 9
          #   dockernamespace: quay.io/almalinuxorg/almalinux
          # - os: almalinux
          #   version: 10
          #   dockernamespace: quay.io/almalinuxorg/almalinux
    runs-on: ubuntu-latest
    container: 
      image: ${{ matrix.dockernamespace }}:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Make sure awk is present
        run: |
          if [ ${{ matrix.version }} -gt 40 ]; then dnf5 install gawk -y; else dnf install gawk -y; fi

      - name: Get version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ inputs.version }}" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "push" ]; then
            # Extract version from tag (e.g., v1.14.11-1 -> 1.14.11)
            echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//' | sed 's/-[^-]*$//')" >> $GITHUB_ENV
          else
            echo "VERSION=$(grep ^VERSION Makefile | awk -F:= '{print $2}' | tr -d ' ')" >> $GITHUB_ENV
          fi
      
      - name: Get release
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ inputs.release }}" ]; then
            echo "RELEASE=${{ inputs.release }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "push" ]; then
            # Extract release from tag (e.g., v1.14.11-1 -> 1)
            echo "RELEASE=$(echo ${{ github.ref_name }} | sed 's/^v//' | sed 's/^.*-//')" >> $GITHUB_ENV
          else
            echo "RELEASE=$(grep ^RELEASE Makefile | awk -F:= '{print $2}' | tr -d ' ')" >> $GITHUB_ENV
          fi

      - name: Specify A Target For make
        run: |
          echo "SPECIFICTARGET=github-release" >> $GITHUB_ENV

      - name: Environment variable for setting name of RPM when using EVDI from Github
        run: |
          echo "EVDISOURCE=.github_evdi" >> $GITHUB_ENV

      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV
     
      - name: Run CI
        run: ci/${{ matrix.os }}.sh

      - name: Rename files
        run : ls -la
      - run: mv displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.src.rpm ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.src.rpm
      - run: mv x86_64/displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.x86_64.rpm ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.x86_64.rpm
      - run: chown `id -u`:`id -g` -R .

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}-x86_64
          path: ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm

      - name: Upload Assets To Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: '${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm'
          draft: false
          update_latest_release: true
          tags: true
          overwrite: true
          tag_name: v${{ env.VERSION }}-${{ env.RELEASE }}

  # buildrpms-arm:
  #   needs: buildrpms-x86-64
  #   strategy:
  #     matrix:
  #       include:
  #         - os: fedora
  #           version: 40
  #           dockernamespace: quay.io/fedora/fedora
  #         - os: fedora
  #           version: 41
  #           dockernamespace: quay.io/fedora/fedora
  #         - os: fedora
  #           version: 42
  #           dockernamespace: quay.io/fedora/fedora
  #         - os: centos-stream
  #           version: stream9
  #           dockernamespace: quay.io/centos/centos
  #         - os: rocky
  #           version: 9
  #           dockernamespace: quay.io/rockylinux/rockylinux
  #         - os: rocky
  #           version: 10
  #           dockernamespace: quay.io/rockylinux/rockylinux
  #         - os: almalinux
  #           version: 9
  #           dockernamespace: quay.io/almalinuxorg/almalinux
  #         - os: almalinux
  #           version: 10
  #           dockernamespace: quay.io/almalinuxorg/almalinux
  #   runs-on: ubuntu-24.04-arm
  #   container: 
  #     image: ${{ matrix.dockernamespace }}:${{ matrix.version }}
  #   steps:
  #     - uses: actions/checkout@v4
  # 
  #     - name: Make sure awk is present
  #       run: |
  #         if [ ${{ matrix.version }} -gt 40 ]; then dnf5 install gawk -y; else dnf install gawk -y; fi
  # 
  #     - name: Get version
  #       run: |
  #         echo "VERSION=$(grep ^VERSION Makefile | awk -F:= '{print $2}' | tr -d ' ')" >> $GITHUB_ENV
  #     
  #     - name: Get release
  #       run: |
  #         echo "RELEASE=$(grep ^RELEASE Makefile | awk -F:= '{print $2}' | tr -d ' ')" >> $GITHUB_ENV
  # 
  #     - name: Specify A Target For make
  #       run: |
  #         echo "SPECIFICTARGET=github-release" >> $GITHUB_ENV
  # 
  #     - name: Environment variable for setting name of RPM when using EVDI from Github
  #       run: |
  #         echo "EVDISOURCE=.github_evdi" >> $GITHUB_ENV
  # 
  #     - name: Environment variable for OS version
  #       run: |
  #         echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV
  #     
  #     - name: Run CI
  #       run: ci/${{ matrix.os }}.sh
  # 
  #     - name: Rename files
  #       run : ls -la
  #     - run: mv aarch64/displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.aarch64.rpm ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.aarch64.rpm
  #     - run: chown `id -u`:`id -g` -R .
  # 
  #     - name: Upload RPM
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}-aarch64
  #         path: ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm
  # 
  #     - name: Upload Assets To Release
  #       uses: xresloader/upload-to-github-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         file: '${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm'
  #         draft: false
  #         update_latest_release: true
  #         tags: true
  #         overwrite: true
